// src/lib/aiCoach.js
//
// Turns a completed rep's raw data (which checks passed/failed, and the
// actual angles reached) into one spoken sentence, generated by Claude on
// the server -- see api/coach-feedback.js. The API key never reaches the
// browser: this just POSTs the numbers and gets text back.

const ENDPOINT = '/api/coach-feedback';
const REQUEST_TIMEOUT_MS = 4000;

// Short, plain fallback phrases, used ONLY when the AI request fails,
// times out, or the browser is offline -- so a rep is never met with
// silence. These intentionally aren't the primary feedback path.
const FALLBACK_SNIPPETS = {
  NOT_DEEP_ENOUGH: 'go a little lower',
  LEANING_FORWARD: 'keep your chest up',
  NOT_CURLED_ENOUGH: 'curl all the way up',
  USING_MOMENTUM: 'try not to swing the weight',
  HIPS_SAGGING: 'keep your hips in line',
  NOT_FULL_LOCKOUT: 'press all the way to lockout',
  ARCHING_BACK: "don't arch your back",
};

function buildFallbackMessage(codes) {
  const snippets = codes.map((code) => FALLBACK_SNIPPETS[code]).filter(Boolean);
  if (snippets.length === 0) return 'Nice rep.';
  return `Rep counted -- ${snippets.join(', and ')}.`;
}

// `codes` is every issue code from this rep's events (or just
// ['REP_COUNTED'] for a clean rep). `metrics` is the analyzer's full result
// for this frame (angles, side, phase, repSummary, ...) so the model has
// real numbers to reference instead of just the pass/fail codes.
export async function getCoachFeedback({ exerciseId, codes, repCount, metrics }) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  try {
    const response = await fetch(ENDPOINT, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ exerciseId, codes, repCount, metrics }),
      signal: controller.signal,
    });

    if (!response.ok) {
      throw new Error(`coach-feedback responded ${response.status}`);
    }

    const data = await response.json();
    if (typeof data.message !== 'string' || !data.message.trim()) {
      throw new Error('coach-feedback returned no message');
    }

    return data.message.trim();
  } catch (error) {
    console.warn('aiCoach: falling back to a local message', error);
    return buildFallbackMessage(codes);
  } finally {
    clearTimeout(timeout);
  }
}
